"""Config file for model parameters"""

BIOMASS_AV_TS_START_YEAR = 2020
BIOMASS_AV_TS_END_YEAR = 2050
BIOMASS_AV_TS_END_VALUE = 2000

CARBON_TAX_START_YEAR = 2020
CARBON_TAX_END_YEAR = 2050
CARBON_TAX_START_VALUE = 0
CARBON_TAX_END_VALUE = 210

ELECTRICITY_PRICE_START_YEAR = 2020
ELECTRICITY_PRICE_MID_YEAR = 2035
ELECTRICITY_PRICE_END_YEAR = 2050

HYDROGEN_PRICE_START_YEAR = 2020
HYDROGEN_PRICE_END_YEAR = 2050

EMISSIONS_FACTOR_SLAG = 0.55
ENERGY_DENSITY_MET_COAL=28 #[MJ/kg]

DISCOUNT_RATE = 0.07
EUR_USD_CONVERSION = 0.877

# Define Data Path
IMPORT_DATA_PATH = "./data/import_data"
PKL_FOLDER = "./data/pkl_data"
