"""Config file for model parameters"""

BIOMASS_AV_TS_START_YEAR = 2020
BIOMASS_AV_TS_END_YEAR = 2050
BIOMASS_AV_TS_END_VALUE = 2000

CARBON_TAX_START_YEAR = 2020
CARBON_TAX_END_YEAR = 2050
CARBON_TAX_START_VALUE = 0
CARBON_TAX_END_VALUE = 210

ELECTRICITY_PRICE_START_YEAR = 2020
ELECTRICITY_PRICE_END_YEAR = 2050

# Define Data Path
IMPORT_DATA_PATH = "./import_data"
PKL_FOLDER = "./pkl_data"
